### ISSUE TITLE
the application is not starting

### ISSUE THREAD

**Issue by Markokry** [otamurod/MyTaxi#7]
[error.txt](https://github.com/user-attachments/files/16588589/error.txt)
![image](https://github.com/user-attachments/assets/2c1189d0-1bcf-4810-a602-b1389f20966d)

error descriptions are in the text file

**Comment by otamurod** [comment]
**Everything is fine on my side**. And you will have the same. See, **you are Unauthorized** to **dowload Mapbox dependencies** since it **requires a Secret key**. I have removed my own secret key since the Mapbox can charge me if the request limit exceeds.

**But this will not be a problem for you if you follow the guidelines as in the README file.**

Here is a quick recap:
1. Sign up to MapBox
2. Create your own new Secret key. Be sure to have a Secret key with a download option checked. Public key will not work.
3. Add a new gradle file to project's root directory, named keystore.properties. Then you should place your MapBox Secret key in the file with an identifier as described in the README.
4. You are good to go. You can build and run the app.

**I used latest Android Studio version. So be sure to configure your local repository properly to get the app running.**

Hope it helps.

If you have further questions, do not hesitate to contact.

**Comment by otamurod** [comment]
All steps to overcome the build error explained
